baseURL = "https://blog.nickelp.ro"
languageCode = "en-us"
title = "nickelp.ro"
theme = "1800"

[params]
  homeURL = "https://nickelp.ro"
  description = "Personal Site"
  githubUsername = "nickelpro"
  twitterUsername = "VitoGamberini"
  redditUsername = "not_a_novel_account"
  instagramUsername = "vito.gamberini"
  tagline = "Taglines are for nerds"

[params.work]
  jobTitle = "Deep Sea Noodle"

[author]
  fullname = "Nicholas Vito Gamberini"
  name = "Vito Gamberini"

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  noClasses = false
